/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccountSessions: () => import('#controllers/account_sessions_controller'),
  AdminSessions: () => import('#controllers/admin_sessions_controller'),
  admin: {
    Activity: () => import('#controllers/admin/activity_controller'),
    Jobs: () => import('#controllers/admin/jobs_controller'),
    Notifications: () => import('#controllers/admin/notifications_controller'),
    OrgUnits: () => import('#controllers/admin/org_units_controller'),
    Roles: () => import('#controllers/admin/roles_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Setup: () => import('#controllers/admin/setup_controller'),
    Support: () => import('#controllers/admin/support'),
    Templates: () => import('#controllers/admin/templates_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  Assignments: () => import('#controllers/assignments_controller'),
  Attachments: () => import('#controllers/attachments_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RecordCollaboration: () => import('#controllers/record_collaboration_controller'),
  Resources: () => import('#controllers/resources_controller'),
  SavedViews: () => import('#controllers/saved_views_controller'),
  Session: () => import('#controllers/session_controller'),
  UserInvitations: () => import('#controllers/user_invitations_controller'),
}
