/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Customers: () => import('#controllers/customers_controller'),
  Session: () => import('#controllers/session_controller'),
}
