import type { ResourceRegistry } from '../resource/registry.js'
import { KIT_VERSION } from '../version.js'

/** Field kinds accepted by defineResource, with their storage. */
export const FIELD_TYPES: Record<string, string> = {
  string: 'varchar',
  text: 'text',
  integer: 'integer',
  money: 'bigint minor units, decimal string in JSON',
  boolean: 'boolean',
  date: 'date (YYYY-MM-DD)',
  datetime: 'timestamptz',
  json: 'jsonb',
  attachment: 'attachments row id; per-field accept/maxSize',
  belongsTo: 'foreign key, preloaded, restrict on delete',
  hasMany: 'child resource; inline rows saved with the parent',
  lookup: 'lookups group key',
}
export const FIELD_OPTIONS = [
  'required',
  'unique (partial, active rows)',
  'sortable',
  'searchable (generated tsvector)',
  'filterable',
  'permissionLevel',
  'sequence',
  'column',
]
export const RESOURCE_OPTIONS = [
  'scoped (required)',
  'submittable (docStatus, submit/cancel/amend-by-copy)',
  'version (optimistic locking, default with submittable)',
  'customFields',
  'list / form / show / serialize / hidden',
  'actions',
  'hooks.beforeSave / hooks.afterSave',
]
export const CONDITION_OPERATORS = ['$eq', '$ne', '$in', '$lt', '$gt', '$like']
export const WORKFLOW_STEPS = ['condition', 'update', 'notify', 'approval', 'delay', 'http', 'end']

/**
 * Kit services by concern. Every name is a public export of @adula/kit; a test
 * checks this list against the package entry so the catalog cannot drift.
 */
export const SERVICES: Record<string, string[]> = {
  'Resources and authorization': [
    'defineResource',
    'ResourceRegistry',
    'ResourceService',
    'createResourceController',
    'buildAbility',
    'accessibleBy',
    'ActorStore',
    'packedResourceRules',
  ],
  'Records and collaboration': [
    'RecordCollaboration',
    'followerListeners',
    'Assignments',
    'SavedViews',
    'logActivity',
  ],
  'Documents and workflows': ['defineWorkflow', 'WorkflowEngine', 'workflowListeners'],
  'Notifications and messages': [
    'notify',
    'notifyWithTemplate',
    'MessageTemplates',
    'deliverNotificationMail',
    'listenForNotifications',
    'NotificationsAdmin',
  ],
  'Integration': [
    'Webhooks',
    'signWebhook',
    'openApiDocument',
    'ImportBatches',
    'renderPrintHtml',
    'htmlToPdf',
  ],
  'Security': ['TwoFactor', 'UserInvitations', 'UsersAdmin', 'RolesAdmin'],
  'Data and operations': [
    'sequence',
    'Settings',
    'SettingsAdmin',
    'publishOutbox',
    'consumeEvent',
    'recordMutation',
    'moveOrgUnit',
    'migrateStorage',
    'verifyBackup',
    'runtimeHealth',
  ],
}
export const EXTENSION_POINTS = [
  'Resource hooks (beforeSave, afterSave) inside the save transaction',
  'Page override: inertia/pages/<resource>/{index,form,show}.tsx replaces the generated page',
  'Domain events <module>.<resource>.{created,updated,deleted,submitted,cancelled,amended} with idempotent listeners',
  'Module workflows (Module.workflows) with versioned definitions',
  'Message templates edited per deployment',
  'Outgoing webhooks and the bearer-token /api/v1 API',
]
export const OUTSIDE_THE_KIT = [
  'Dynamic fields or a field editor screen',
  'Runtime plugins',
  'A visual workflow editor',
  'Multi-tenant SaaS in one database (one deployment per organization)',
  'XLSX import until a maintained parser passes the dependency rule (GAP-006)',
]

/** The capability catalog read by idea-review: generated, never hand-edited. */
export function capabilityCatalog(
  options: { registry?: ResourceRegistry; commands?: string[] } = {}
) {
  const lines = [
    `# adula-kit capabilities (${KIT_VERSION})`,
    '',
    'Generated by `node ace adula:capabilities`. Read this before proposing a module; anything not listed here is not provided by the kit.',
    '',
    '## Resource definition',
    '',
    '| Field type | Storage |',
    '|---|---|',
    ...Object.entries(FIELD_TYPES).map(([type, storage]) => `| ${type} | ${storage} |`),
    '',
    `Field options: ${FIELD_OPTIONS.join(', ')}.`,
    '',
    `Resource options: ${RESOURCE_OPTIONS.join(', ')}.`,
    '',
    `Role rule conditions: ${CONDITION_OPERATORS.join(', ')} on scalar fields; unsupported conditions are refused. Organization scope is always added with AND.`,
    '',
    `Workflow steps: ${WORKFLOW_STEPS.join(', ')}.`,
    '',
    '## Services',
    '',
    ...Object.entries(SERVICES).map(
      ([area, names]) => `- **${area}:** ${names.map((name) => `\`${name}\``).join(', ')}`
    ),
    '',
    '## Extension points',
    '',
    ...EXTENSION_POINTS.map((point) => `- ${point}`),
    '',
    '## Outside the kit',
    '',
    ...OUTSIDE_THE_KIT.map((point) => `- ${point}`),
  ]
  if (options.commands?.length)
    lines.push('', '## Commands', '', ...options.commands.map((command) => `- \`${command}\``))
  if (options.registry) {
    lines.push('', '## This project', '')
    const modules = options.registry.modules()
    if (!modules.length) lines.push('No modules are registered yet.')
    for (const module of modules) {
      lines.push(`### ${module.name} — ${module.label.ar}`, '')
      if (module.dependsOn.length) lines.push(`Depends on: ${module.dependsOn.join(', ')}`, '')
      for (const resource of module.resources)
        lines.push(
          `- \`${resource.name}\` (${resource.label.ar}; ${resource.scoped ? 'scoped' : 'central'}${resource.submittable ? ', submittable' : ''}): ${Object.entries(
            resource.fields
          )
            .map(
              ([key, field]) =>
                `${key}:${field.type}${'resource' in field ? `→${field.resource}` : ''}`
            )
            .join(', ')}`
        )
      for (const workflow of module.workflows ?? [])
        lines.push(
          `- workflow \`${workflow.name}@${workflow.version}\` on ${workflow.resource}: ${Object.keys(workflow.steps).join(' → ')}`
        )
      lines.push('')
    }
  }
  return `${lines.join('\n').trimEnd()}\n`
}
