/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivitySchema extends BaseModel {
  static $columns = [
    'action',
    'actorId',
    'changes',
    'createdAt',
    'id',
    'recordId',
    'resource',
  ] as const
  $columns = ActivitySchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: number
  @column()
  declare changes: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare recordId: number
  @column()
  declare resource: string
}

export class AttachmentSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'data',
    'deletedAt',
    'disk',
    'extname',
    'field',
    'id',
    'mimeType',
    'name',
    'orgUnitId',
    'originalName',
    'path',
    'recordId',
    'resource',
    'size',
    'uploadedBy',
  ] as const
  $columns = AttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare disk: string
  @column()
  declare extname: string
  @column()
  declare field: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare name: string
  @column()
  declare orgUnitId: number | null
  @column()
  declare originalName: string
  @column()
  declare path: string
  @column()
  declare recordId: number | null
  @column()
  declare resource: string | null
  @column()
  declare size: bigint | number
  @column()
  declare uploadedBy: number
}

export class AuthorizationRevisionSchema extends BaseModel {
  static $columns = ['id', 'version'] as const
  $columns = AuthorizationRevisionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare version: bigint | number
}

export class CustomerSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'deletedAt',
    'email',
    'id',
    'name',
    'searchVector',
    'updatedAt',
    'updatedBy',
  ] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare searchVector: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number
}

export class LookupSchema extends BaseModel {
  static $columns = ['active', 'group', 'id', 'key', 'labelAr', 'labelEn', 'sort'] as const
  $columns = LookupSchema.$columns
  @column()
  declare active: boolean | null
  @column()
  declare group: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare labelAr: string
  @column()
  declare labelEn: string
  @column()
  declare sort: number | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'readAt', 'title', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare userId: number
}

export class OrderLineSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'deletedAt',
    'description',
    'id',
    'orderId',
    'orgUnitId',
    'quantity',
    'updatedAt',
    'updatedBy',
    'version',
  ] as const
  $columns = OrderLineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare orgUnitId: number
  @column()
  declare quantity: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number
  @column()
  declare version: number
}

export class OrderSchema extends BaseModel {
  static $columns = [
    'amendedFromId',
    'contract',
    'createdAt',
    'createdBy',
    'customerId',
    'deletedAt',
    'docStatus',
    'id',
    'internalNote',
    'issuedAt',
    'notes',
    'number',
    'orgUnitId',
    'searchVector',
    'status',
    'total',
    'updatedAt',
    'updatedBy',
    'version',
  ] as const
  $columns = OrderSchema.$columns
  @column()
  declare amendedFromId: number | null
  @column()
  declare contract: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare customerId: number | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare docStatus: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare internalNote: string | null
  @column.date()
  declare issuedAt: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare number: string
  @column()
  declare orgUnitId: number
  @column()
  declare searchVector: string | null
  @column()
  declare status: string | null
  @column()
  declare total: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number
  @column()
  declare version: number
}

export class OrgUnitSchema extends BaseModel {
  static $columns = ['id', 'name', 'parentId', 'path', 'type'] as const
  $columns = OrgUnitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column()
  declare path: any
  @column()
  declare type: string
}

export class OutboxSchema extends BaseModel {
  static $columns = [
    'attempts',
    'createdAt',
    'event',
    'id',
    'lastError',
    'payload',
    'publishedAt',
  ] as const
  $columns = OutboxSchema.$columns
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastError: string | null
  @column()
  declare payload: any
  @column.dateTime()
  declare publishedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenHash', 'usedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class ProcessedEventSchema extends BaseModel {
  static $columns = ['eventId', 'listener', 'processedAt'] as const
  $columns = ProcessedEventSchema.$columns
  @column({ isPrimary: true })
  declare eventId: string
  @column()
  declare listener: string
  @column.dateTime()
  declare processedAt: DateTime | null
}

export class RoleRuleSchema extends BaseModel {
  static $columns = [
    'action',
    'conditions',
    'fields',
    'id',
    'inverted',
    'roleId',
    'subject',
  ] as const
  $columns = RoleRuleSchema.$columns
  @column()
  declare action: string
  @column()
  declare conditions: any | null
  @column()
  declare fields: any | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inverted: boolean
  @column()
  declare roleId: number
  @column()
  declare subject: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'permissionLevel'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare permissionLevel: number
}

export class SavedViewSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'name',
    'query',
    'resource',
    'shared',
    'updatedAt',
    'userId',
  ] as const
  $columns = SavedViewSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare query: any
  @column()
  declare resource: string
  @column()
  declare shared: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class SequenceSchema extends BaseModel {
  static $columns = ['key', 'value'] as const
  $columns = SequenceSchema.$columns
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare value: bigint | number
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
}

export class SettingSchema extends BaseModel {
  static $columns = ['id', 'key', 'scope', 'scopeId', 'value'] as const
  $columns = SettingSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare scope: string
  @column()
  declare scopeId: string
  @column()
  declare value: any
}

export class SocialAccountSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'provider', 'providerId', 'userId'] as const
  $columns = SocialAccountSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare provider: string
  @column()
  declare providerId: string
  @column()
  declare userId: number
}

export class TaskSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'deletedAt',
    'done',
    'id',
    'orderId',
    'orgUnitId',
    'searchVector',
    'title',
    'updatedAt',
    'updatedBy',
  ] as const
  $columns = TaskSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare done: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
  @column()
  declare orgUnitId: number
  @column()
  declare searchVector: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: number
}

export class UserInvitationSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'createdAt',
    'email',
    'expiresAt',
    'fullName',
    'id',
    'invitedBy',
    'tokenHash',
  ] as const
  $columns = UserInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedBy: number | null
  @column()
  declare tokenHash: string
}

export class UserOrgUnitSchema extends BaseModel {
  static $columns = ['id', 'orgUnitId', 'userId'] as const
  $columns = UserOrgUnitSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgUnitId: number | null
  @column()
  declare userId: number
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['id', 'orgUnitId', 'roleId', 'userId'] as const
  $columns = UserRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orgUnitId: number | null
  @column()
  declare roleId: number
  @column()
  declare userId: number
}

export class UserSessionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'ip',
    'lastSeenAt',
    'revokedAt',
    'userAgent',
    'userId',
  ] as const
  $columns = UserSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ip: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'disabledAt',
    'email',
    'emailVerifiedAt',
    'fullName',
    'id',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare disabledAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkflowRunSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'definition',
    'definitionVersion',
    'id',
    'recordId',
    'resource',
    'snapshot',
    'status',
  ] as const
  $columns = WorkflowRunSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare definition: string
  @column()
  declare definitionVersion: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare recordId: number
  @column()
  declare resource: string
  @column()
  declare snapshot: any
  @column()
  declare status: string
}
